// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-L5TeFHZ-wd7u60EAnR18jXr_j4yW-eQ',
    appId: '1:164390119672:web:ac6d71fdc5da942aaf730d',
    messagingSenderId: '164390119672',
    projectId: 'amud-7a475',
    authDomain: 'amud-7a475.firebaseapp.com',
    storageBucket: 'amud-7a475.firebasestorage.app',
    measurementId: 'G-019CP4J63H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf9ooFxlQQiqlhmJN38EjpiX73a9EmdVs',
    appId: '1:164390119672:android:d0835229ebc160c0af730d',
    messagingSenderId: '164390119672',
    projectId: 'amud-7a475',
    storageBucket: 'amud-7a475.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1paud8YufhX7oLD_cVQaA-zs0flqLDW8',
    appId: '1:164390119672:ios:887b0f431f54902daf730d',
    messagingSenderId: '164390119672',
    projectId: 'amud-7a475',
    storageBucket: 'amud-7a475.firebasestorage.app',
    iosBundleId: 'page.amud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1paud8YufhX7oLD_cVQaA-zs0flqLDW8',
    appId: '1:164390119672:ios:887b0f431f54902daf730d',
    messagingSenderId: '164390119672',
    projectId: 'amud-7a475',
    storageBucket: 'amud-7a475.firebasestorage.app',
    iosBundleId: 'page.amud',
  );
}
