#!/usr/bin/env python3
"""Writes corpus/ISSUES.md: every issue the taggers reported (missing or
misplaced text, wrong vowels, ambiguities, alignment gaps…), by siddur and
type, for reconciling the corpus and reporting source errors upstream.

    python3 tool/corpus/issues_report.py
"""
import collections
import glob
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
CORPUS = os.path.join(ROOT, 'corpus')

# Most actionable first: problems in the source text, then tagging doubts.
ORDER = ['missing_text', 'misplaced', 'duplicate', 'wrong_vowel', 'engine_bug_risk', 'ambiguous', 'alignment',
         'new_variable', 'new_minhag']
TITLES = {
    'missing_text': 'Missing text in the source',
    'misplaced': 'Misplaced text',
    'duplicate': 'Duplicated text',
    'wrong_vowel': 'Wrong vowels',
    'engine_bug_risk': 'Risks for the engine',
    'ambiguous': 'Ambiguous tagging',
    'alignment': 'English alignment gaps',
    'new_variable': 'Variables the taggers needed',
    'new_minhag': 'Customs the taggers needed',
}


def main():
    by = collections.defaultdict(lambda: collections.defaultdict(list))
    for path in sorted(glob.glob(os.path.join(CORPUS, 'tagged', '*', '*.json'))):
        nusach = os.path.basename(os.path.dirname(path))
        for issue in json.load(open(path)).get('issues', []):
            by[nusach][issue.get('type', '?')].append(issue)
    total = sum(len(v) for t in by.values() for v in t.values())
    out = ['# Corpus issues', '',
           f'{total} issues reported while tagging, generated by `tool/corpus/issues_report.py`. '
           'Corrections applied at build time live in `tool/corpus/reconcile.py`.', '']
    out.append('| Siddur | ' + ' | '.join(TITLES[t] for t in ORDER) + ' |')
    out.append('|---|' + '---|' * len(ORDER))
    for nusach in sorted(by):
        out.append(f'| {nusach} | ' + ' | '.join(str(len(by[nusach].get(t, []))) for t in ORDER) + ' |')
    for nusach in sorted(by):
        out += ['', f'## {nusach}']
        for t in ORDER:
            issues = by[nusach].get(t)
            if not issues:
                continue
            out += ['', f'### {TITLES[t]} ({len(issues)})', '']
            for i in issues:
                where = i.get('id', '').split(':', 1)[-1]
                detail = ' '.join(str(i.get('detail', '')).split())
                out.append(f'- `{where}`: {detail}')
    with open(os.path.join(CORPUS, 'ISSUES.md'), 'w') as f:
        f.write('\n'.join(out) + '\n')
    print(f'corpus/ISSUES.md: {total} issues')


if __name__ == '__main__':
    main()
