#!/usr/bin/env python3
"""Generates lib/src/data/*.g.dart from upstream hebcal sources.

Usage: gen_data.py <dir containing hdate-js, hebcal-es6, hebcal-learning clones>
"""
import json, os, re, sys, unicodedata

SRC = sys.argv[1]
OUT = os.path.join(os.path.dirname(__file__), '..', 'lib', 'src', 'data')
HEADER = '// GENERATED by tool/gen_data.py from upstream hebcal sources. DO NOT EDIT.\n// ignore_for_file: constant_identifier_names, lines_longer_than_80_chars\n\n'


def dstr(s):
    return "'" + s.replace('\\', '\\\\').replace("'", "\\'").replace('$', '\\$').replace('\n', '\\n') + "'"


def lit(v):
    if isinstance(v, bool):
        return 'true' if v else 'false'
    if v is None:
        return 'null'
    if isinstance(v, (int, float)):
        return repr(v)
    if isinstance(v, str):
        return dstr(v)
    if isinstance(v, list):
        return '[' + ', '.join(lit(x) for x in v) + ']'
    if isinstance(v, dict):
        return '{' + ', '.join(dstr(k) + ': ' + lit(x) for k, x in v.items()) + '}'
    raise TypeError(v)


def parse_po(path):
    out = {}
    cur_id = cur_str = None
    mode = None
    for line in open(path, encoding='utf-8'):
        line = unicodedata.normalize('NFC', line.strip())
        if line.startswith('msgid '):
            if cur_id is not None and cur_str:
                out[cur_id] = cur_str
            cur_id = json.loads(line[6:]); cur_str = None; mode = 'id'
        elif line.startswith('msgstr '):
            cur_str = json.loads(line[7:]); mode = 'str'
        elif line.startswith('"'):
            if mode == 'id': cur_id += json.loads(line)
            elif mode == 'str': cur_str += json.loads(line)
        elif not line:
            mode = None
    if cur_id is not None and cur_str:
        out[cur_id] = cur_str
    out.pop('', None)
    return out


def write(name, body):
    with open(os.path.join(OUT, name), 'w', encoding='utf-8') as f:
        f.write(HEADER + body)


# ---- locales
locs = {}
for loc in ['he', 'ashkenazi']:
    m = {}
    for repo in ['hdate-js', 'hebcal-es6', 'hebcal-learning']:
        p = os.path.join(SRC, repo, 'po', loc + '.po')
        if os.path.exists(p):
            m.update(parse_po(p))
    locs[loc] = m
nonikud = parse_po(os.path.join(SRC, 'hebcal-es6', 'po', 'he-x-NoNikud.po'))
write('locale_data.g.dart',
      'const Map<String, String> poHe = ' + lit(locs['he']) + ';\n\n'
      'const Map<String, String> poAshkenazi = ' + lit(locs['ashkenazi']) + ';\n\n'
      'const Map<String, String> poHeNoNikudOverride = ' + lit(nonikud) + ';\n')

# ---- core data
core = os.path.join(SRC, 'hebcal-es6', 'src')
cities = json.load(open(os.path.join(core, 'cities.json')))
sefira = json.load(open(os.path.join(core, 'sefira.json')))
write('core_data.g.dart',
      'const List<String> citiesData = ' + lit(cities) + ';\n\n'
      'const List<String> ps67lines = ' + lit(sefira['ps67lines']) + ';\n\n'
      'const List<String> anaBekoach = ' + lit(sefira['anaBekoach']) + ';\n\n'
      'const String lamnatzeachLetters = ' + lit(sefira['lamnatzeachLetters']) + ';\n')

# ---- learning data
ls = os.path.join(SRC, 'hebcal-learning', 'src')
def lj(n):
    return json.load(open(os.path.join(ls, n)))
body = ''
for var, fn in [('bavliJson', 'bavli.json'), ('mishnayotJson', 'mishnayot.json'),
                ('tanakhNumChapJson', 'tanakhNumChap.json'), ('mishnehTorahJson', 'mishnehTorah.json'),
                ('seferHaMitzvotJson', 'seferHaMitzvot.json'), ('kitzurSaJson', 'kitzurSa.json'),
                ('arukhHaShulchanYomiJson', 'arukhHaShulchanYomi.json'), ('amudimJson', 'amudim.json'),
                ('dirshuDafHalachaJson', 'dirshuDafHalacha.json'), ('masoreticJson', 'masoretic.json'),
                ('shekalimDafYomiMapJson', 'shekalimDafYomiMap.json'),
                ('yerushalmiVilnaMapJson', 'yerushalmiVilnaMap.json')]:
    body += 'const ' + var + ' = ' + lit(lj(fn)) + ';\n\n'
write('learning_data.g.dart', body)

# ---- table literals copied from TS sources (JS array syntax is valid Dart)
def extract(path, start_pat):
    s = open(path, encoding='utf-8').read()
    s = re.sub(r'/\*.*?\*/', '', s, flags=re.S)
    i = s.index(start_pat) + len(start_pat) - 1
    depth = 0
    for j in range(i, len(s)):
        c = s[j]
        if c == '[': depth += 1
        elif c == ']':
            depth -= 1
            if depth == 0:
                txt = s[i:j + 1]
                txt = re.sub(r'//[^\n]*', '', txt)
                return txt.replace('$', '\\$').replace('undefined', 'null')
    raise ValueError(start_pat)

months = '''const Nisan = 1;
const Iyyar = 2;
const Sivan = 3;
const Tamuz = 4;
const Av = 5;
const Elul = 6;
const Tishrei = 7;
const Cheshvan = 8;
const Kislev = 9;
const Teves = 10;
const Shvat = 11;
const Adar = 12;
const Adar1 = 12;
const Adar2 = 13;
'''
cc = os.path.join(ls, 'chofetzChaimBase.ts')
sh = os.path.join(ls, 'shemiratHaLashonBase.ts')
write('learning_tables.g.dart', months + '''
const Hakdamah = 'Hakdamah';
const Psichah = 'Psichah';
const Lavin = 'Lavin';
const Asin = 'Asin';
const Arurin = 'Arurin';
const HilchosLH = 'HilchosLH';
const HilchosRechilus = 'HilchosRechilus';
const Tziyurim = 'Tziyurim';

const List<List<Object?>> chofetzChaimSimple = ''' + extract(cc, 'const simple = [') + ''';

const List<List<Object?>> chofetzChaimLeap = ''' + extract(cc, 'const leap = [') + ''';

const Book1 = 1;
const Book2 = 2;
const Shar_Hazechira = 'Shar Hazechira';
const Shar_Hatorah = 'Shar Hatorah';
const Shar_Hatvuna = 'Shar Hatvuna';
const Epilogue = 'Chasimas Hasefer';
const Chapters = 'x';

const List<List<Object?>> shemiratHaLashonSchedule = ''' + extract(sh, 'const schedule: Entry[] = [') + ''';
''')
print('ok')
