// GENERATED by tool/gen_service_worker.dart — do not edit.
// Precaches the app shell, every Sefaria text/rule/font and one CanvasKit build.
const CACHE = 'amud-ff95689e';
const RUNTIME = 'amud-runtime';
const PRECACHE = [
  "./",
  ".last_build_id",
  "assets/AssetManifest.bin",
  "assets/AssetManifest.bin.json",
  "assets/FontManifest.json",
  "assets/NOTICES",
  "assets/assets/fonts/AharoniCLM-Bold.otf",
  "assets/assets/fonts/AharoniCLM-Book.otf",
  "assets/assets/fonts/DavidCLM-Bold.otf",
  "assets/assets/fonts/DavidCLM-Medium.otf",
  "assets/assets/fonts/DavidLibre-Bold.ttf",
  "assets/assets/fonts/DavidLibre-Regular.ttf",
  "assets/assets/fonts/DrugulinCLM-Bold.otf",
  "assets/assets/fonts/ElliniaCLM-Bold.otf",
  "assets/assets/fonts/ElliniaCLM-Light.otf",
  "assets/assets/fonts/EzraSIL.ttf",
  "assets/assets/fonts/EzraSILSR.ttf",
  "assets/assets/fonts/FrankRuehlCLM-Bold.otf",
  "assets/assets/fonts/FrankRuehlCLM-Medium.otf",
  "assets/assets/fonts/FrankRuhlLibre.ttf",
  "assets/assets/fonts/Fraunces-Amud.ttf",
  "assets/assets/fonts/GPL-2.0-Culmus.txt",
  "assets/assets/fonts/HadasimCLM-Bold.otf",
  "assets/assets/fonts/HadasimCLM-Regular.otf",
  "assets/assets/fonts/KeterAramTsova.ttf",
  "assets/assets/fonts/KeterYG-Bold.ttf",
  "assets/assets/fonts/KeterYG-Medium.ttf",
  "assets/assets/fonts/LICENSE-Culmus.txt",
  "assets/assets/fonts/LICENSE-KeterAramTsova.txt",
  "assets/assets/fonts/LICENSE-TaameyAshkenaz.txt",
  "assets/assets/fonts/LICENSE-TaameyDavidCLM.txt",
  "assets/assets/fonts/LICENSE-TaameyFrankCLM.txt",
  "assets/assets/fonts/MiriamCLM-Bold.otf",
  "assets/assets/fonts/MiriamCLM-Book.otf",
  "assets/assets/fonts/MiriamMonoCLM-Bold.ttf",
  "assets/assets/fonts/MiriamMonoCLM-Book.ttf",
  "assets/assets/fonts/NachlieliCLM-Bold.otf",
  "assets/assets/fonts/NachlieliCLM-Light.otf",
  "assets/assets/fonts/NotoSerifHebrew.ttf",
  "assets/assets/fonts/OFL-DavidLibre.txt",
  "assets/assets/fonts/OFL-EzraSIL.txt",
  "assets/assets/fonts/OFL-FrankRuhlLibre.txt",
  "assets/assets/fonts/OFL-Fraunces.txt",
  "assets/assets/fonts/OFL-NotoSerifHebrew.txt",
  "assets/assets/fonts/ShofarDemi-Bold.ttf",
  "assets/assets/fonts/ShofarRegular.ttf",
  "assets/assets/fonts/SimpleCLM-Bold.ttf",
  "assets/assets/fonts/SimpleCLM-Medium.ttf",
  "assets/assets/fonts/StamAshkenazCLM.ttf",
  "assets/assets/fonts/StamSefaradCLM.ttf",
  "assets/assets/fonts/TaameyAshkenaz-Bold.ttf",
  "assets/assets/fonts/TaameyAshkenaz-Medium.ttf",
  "assets/assets/fonts/TaameyDavidCLM-Bold.ttf",
  "assets/assets/fonts/TaameyDavidCLM-Medium.ttf",
  "assets/assets/fonts/TaameyFrankCLM-Bold.ttf",
  "assets/assets/fonts/TaameyFrankCLM-Medium.ttf",
  "assets/assets/fonts/YehudaCLM-Bold.otf",
  "assets/assets/fonts/YehudaCLM-Light.otf",
  "assets/assets/rules/rules.json",
  "assets/assets/sefaria/manifest.json",
  "assets/assets/sefaria/rabbi_sacks_on_siddur_fb2cf7__en__english_edition_koren_publishers_jerusalem_2017_153f4f.json.gz",
  "assets/assets/sefaria/rabbi_sacks_on_siddur_fb2cf7__index.json.gz",
  "assets/assets/sefaria/shabbat_siddur_sefard_linear_e1f42a__en__sefaria_community_translation_36bfbf.json.gz",
  "assets/assets/sefaria/shabbat_siddur_sefard_linear_e1f42a__en__the_metsudah_siddur_metsudah_publications_1981_e_11192f.json.gz",
  "assets/assets/sefaria/shabbat_siddur_sefard_linear_e1f42a__he__the_metsudah_siddur_metsudah_publications_1981_h_fa2159.json.gz",
  "assets/assets/sefaria/shabbat_siddur_sefard_linear_e1f42a__index.json.gz",
  "assets/assets/sefaria/siddur_ashkenaz_d5b4ae__en__esk_sidur_cce88d.json.gz",
  "assets/assets/sefaria/siddur_ashkenaz_d5b4ae__en__ha_siddur_ha_shalem_1949_43e26a.json.gz",
  "assets/assets/sefaria/siddur_ashkenaz_d5b4ae__en__irat_dvora_cs_ff080a.json.gz",
  "assets/assets/sefaria/siddur_ashkenaz_d5b4ae__en__irat_dvora_esk_sidur_a3c57e.json.gz",
  "assets/assets/sefaria/siddur_ashkenaz_d5b4ae__en__magyar_imak_nyv_hu_96b4a1.json.gz",
  "assets/assets/sefaria/siddur_ashkenaz_d5b4ae__en__mishnah_yomit_by_dr_joshua_kulp_6d82d2.json.gz",
  "assets/assets/sefaria/siddur_ashkenaz_d5b4ae__en__mourner_s_kaddish_in_aramaic_transliteration_d7b19d.json.gz",
  "assets/assets/sefaria/siddur_ashkenaz_d5b4ae__en__prayer_of_the_state_of_israel_transliterated_b10975.json.gz",
  "assets/assets/sefaria/siddur_ashkenaz_d5b4ae__en__ritual_de_oraciones_para_todo_el_ano_traducci_n__38672b.json.gz",
  "assets/assets/sefaria/siddur_ashkenaz_d5b4ae__en__sefaria_community_translation_36bfbf.json.gz",
  "assets/assets/sefaria/siddur_ashkenaz_d5b4ae__en__sefaria_community_translation_hungarian_hu_6f3b41.json.gz",
  "assets/assets/sefaria/siddur_ashkenaz_d5b4ae__en__siddur_on_the_hill_4254b6.json.gz",
  "assets/assets/sefaria/siddur_ashkenaz_d5b4ae__en__siddur_sha_ar_zahav_4b481b.json.gz",
  "assets/assets/sefaria/siddur_ashkenaz_d5b4ae__en__siddur_sim_shalom_76adcf.json.gz",
  "assets/assets/sefaria/siddur_ashkenaz_d5b4ae__en__sziddur_som_r_jiszr_l_translation_by_rabbi_zsolt_c8cdf5.json.gz",
  "assets/assets/sefaria/siddur_ashkenaz_d5b4ae__en__the_koren_jerusalem_bible_a511f8.json.gz",
  "assets/assets/sefaria/siddur_ashkenaz_d5b4ae__en__the_standard_prayer_book_tr_by_simeon_singer_191_618d75.json.gz",
  "assets/assets/sefaria/siddur_ashkenaz_d5b4ae__en__the_torah_a_women_s_commentary_jps_27211e.json.gz",
  "assets/assets/sefaria/siddur_ashkenaz_d5b4ae__en__translation_based_on_the_metsudah_linear_siddur__68cc72.json.gz",
  "assets/assets/sefaria/siddur_ashkenaz_d5b4ae__he__daat_siddur_ashkenaz_9ff3a5.json.gz",
  "assets/assets/sefaria/siddur_ashkenaz_d5b4ae__he__shema_with_cantillation_0c14dc.json.gz",
  "assets/assets/sefaria/siddur_ashkenaz_d5b4ae__he__siddur_veshinantam_0011d9.json.gz",
  "assets/assets/sefaria/siddur_ashkenaz_d5b4ae__he__tanach_with_nikkud_193d5c.json.gz",
  "assets/assets/sefaria/siddur_ashkenaz_d5b4ae__he__the_metsudah_siddur_1981_ddfac6.json.gz",
  "assets/assets/sefaria/siddur_ashkenaz_d5b4ae__he__the_metsudah_siddur_a_new_linear_siddur_with_eng_17edfd.json.gz",
  "assets/assets/sefaria/siddur_ashkenaz_d5b4ae__he__torat_emet_357_496b06.json.gz",
  "assets/assets/sefaria/siddur_ashkenaz_d5b4ae__he__wikipedia_a1f3dd.json.gz",
  "assets/assets/sefaria/siddur_ashkenaz_d5b4ae__index.json.gz",
  "assets/assets/sefaria/siddur_edot_hamizrach_45b055__en__koren_jerusalem_bible_a00b90.json.gz",
  "assets/assets/sefaria/siddur_edot_hamizrach_45b055__en__psalms_100_tanakh_the_holy_scriptures_published__bb2c04.json.gz",
  "assets/assets/sefaria/siddur_edot_hamizrach_45b055__en__publicado_em_5784_saymon_pires_da_silva_pt_d6cd37.json.gz",
  "assets/assets/sefaria/siddur_edot_hamizrach_45b055__en__sefaria_community_translation_36bfbf.json.gz",
  "assets/assets/sefaria/siddur_edot_hamizrach_45b055__en__shaliehsaboo_edition_ce65c7.json.gz",
  "assets/assets/sefaria/siddur_edot_hamizrach_45b055__en__tanakh_the_holy_scriptures_published_by_jps_2a80c0.json.gz",
  "assets/assets/sefaria/siddur_edot_hamizrach_45b055__en__wikipedia_by_musashiaharon_ad92ef.json.gz",
  "assets/assets/sefaria/siddur_edot_hamizrach_45b055__he__shaliehsaboo_edition_ce65c7.json.gz",
  "assets/assets/sefaria/siddur_edot_hamizrach_45b055__he__shaliehsaboo_edition_eb7de9.json.gz",
  "assets/assets/sefaria/siddur_edot_hamizrach_45b055__he__siddur_edot_hamizrach_temp_5f2e37.json.gz",
  "assets/assets/sefaria/siddur_edot_hamizrach_45b055__he__torat_emet_357_496b06.json.gz",
  "assets/assets/sefaria/siddur_edot_hamizrach_45b055__index.json.gz",
  "assets/assets/sefaria/siddur_sefard_82915d__en__artscroll_cbfed7.json.gz",
  "assets/assets/sefaria/siddur_sefard_82915d__en__eishet_chayil_with_english_159851.json.gz",
  "assets/assets/sefaria/siddur_sefard_82915d__en__koren_steinsaltz_12787f.json.gz",
  "assets/assets/sefaria/siddur_sefard_82915d__en__rabbi_yoni_dahlen_s_translation_c72f1c.json.gz",
  "assets/assets/sefaria/siddur_sefard_82915d__en__sefaria_community_translation_36bfbf.json.gz",
  "assets/assets/sefaria/siddur_sefard_82915d__en__translation_based_on_the_metsudah_linear_siddur__68cc72.json.gz",
  "assets/assets/sefaria/siddur_sefard_82915d__en__yozerot_for_shabbat_shekalim_zachor_piyyutim_for_704edb.json.gz",
  "assets/assets/sefaria/siddur_sefard_82915d__he__modeh_anu_a2b096.json.gz",
  "assets/assets/sefaria/siddur_sefard_82915d__he__the_metsudah_siddur_1981_ddfac6.json.gz",
  "assets/assets/sefaria/siddur_sefard_82915d__he__torat_emet_357_496b06.json.gz",
  "assets/assets/sefaria/siddur_sefard_82915d__index.json.gz",
  "assets/assets/sefaria/the_koren_shalem_siddur_ashkenaz_99667b__en__english_edition_koren_publishers_jerusalem_2017_153f4f.json.gz",
  "assets/assets/sefaria/the_koren_shalem_siddur_ashkenaz_99667b__he__hebrew_edition_koren_publishers_jerusalem_2017_84782b.json.gz",
  "assets/assets/sefaria/the_koren_shalem_siddur_ashkenaz_99667b__index.json.gz",
  "assets/assets/sefaria/weekday_siddur_chabad_d6cb77__en__sefaria_community_translation_36bfbf.json.gz",
  "assets/assets/sefaria/weekday_siddur_chabad_d6cb77__he__wikisource_a17c3d.json.gz",
  "assets/assets/sefaria/weekday_siddur_chabad_d6cb77__index.json.gz",
  "assets/assets/sefaria/weekday_siddur_sefard_linear_499cbc__en__the_metsudah_siddur_a_new_linear_siddur_with_eng_36fca8.json.gz",
  "assets/assets/sefaria/weekday_siddur_sefard_linear_499cbc__he__the_metsudah_siddur_a_new_linear_siddur_with_eng_17edfd.json.gz",
  "assets/assets/sefaria/weekday_siddur_sefard_linear_499cbc__index.json.gz",
  "assets/assets/tehillim/tehillim.json.gz",
  "assets/fonts/MaterialIcons-Regular.otf",
  "assets/packages/cupertino_icons/assets/CupertinoIcons.ttf",
  "assets/packages/flutter_js/assets/js/fetch.js",
  "assets/shaders/ink_sparkle.frag",
  "assets/shaders/stretch_effect.frag",
  "favicon.png",
  "flutter.js",
  "flutter_bootstrap.js",
  "icons/Icon-192.png",
  "icons/Icon-512.png",
  "icons/Icon-maskable-192.png",
  "icons/Icon-maskable-512.png",
  "index.html",
  "main.dart.js",
  "manifest.json",
  "version.json"
];
const CANVASKIT_CHROMIUM = ["canvaskit/chromium/canvaskit.js","canvaskit/chromium/canvaskit.wasm"];
const CANVASKIT_GENERIC = ["canvaskit/canvaskit.js","canvaskit/canvaskit.wasm"];

// Mirrors Flutter's loader: Chromium browsers use the Chromium build.
function canvaskitFiles() {
  const brands = (self.navigator.userAgentData && self.navigator.userAgentData.brands) || [];
  const isChromium = brands.some((b) => b.brand === 'Chromium');
  return isChromium ? CANVASKIT_CHROMIUM : CANVASKIT_GENERIC;
}

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // Fetch in small batches so a slow connection isn't overwhelmed.
    const all = PRECACHE.concat(canvaskitFiles());
    for (let i = 0; i < all.length; i += 8) {
      await cache.addAll(all.slice(i, i + 8).map((u) => new Request(u, {cache: 'reload'})));
    }
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    for (const key of await caches.keys()) {
      if (key !== CACHE && key !== RUNTIME) await caches.delete(key);
    }
    // Same-origin files cached at runtime belong to the old deployment.
    const runtime = await caches.open(RUNTIME);
    for (const req of await runtime.keys()) {
      if (new URL(req.url).origin === location.origin) await runtime.delete(req);
    }
    await self.clients.claim();
  })());
});

self.addEventListener('message', (event) => {
  if (event.data === 'skipWaiting') self.skipWaiting();
});

// Tapping a notification focuses the open app (or opens it) on the page it
// is about (Zmanim for zman alerts).
self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  event.waitUntil((async () => {
    const all = await self.clients.matchAll({type: 'window', includeUncontrolled: true});
    for (const c of all) {
      if ('focus' in c) {
        c.postMessage({type: 'notification-tap', route: event.notification.data || '/zmanim'});
        return c.focus();
      }
    }
    return self.clients.openWindow('./#' + (event.notification.data || '/zmanim'));
  })());
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);

  // App shell: serve cached index.html for navigations (offline-first),
  // refreshing it in the background.
  if (req.mode === 'navigate' && url.origin === location.origin) {
    event.respondWith((async () => {
      const cache = await caches.open(CACHE);
      const cached = await cache.match('./');
      const network = fetch(req).then((res) => {
        if (res.ok) cache.put('./', res.clone());
        return res;
      }).catch(() => undefined);
      return cached || (await network) || Response.error();
    })());
    return;
  }

  // Same-origin assets: cache-first (they're content-versioned by CACHE).
  if (url.origin === location.origin) {
    event.respondWith((async () => {
      // This deployment's precache first, so nothing stale can shadow it.
      const hit = (await (await caches.open(CACHE)).match(req, {ignoreSearch: true})) ||
          (await (await caches.open(RUNTIME)).match(req, {ignoreSearch: true}));
      if (hit) return hit;
      const res = await fetch(req);
      if (res.ok) (await caches.open(RUNTIME)).put(req, res.clone());
      return res;
    })());
    return;
  }

  // Fallback glyph fonts Flutter may request from Google Fonts (emoji,
  // rare scripts), and the Firebase Analytics scripts (versioned URLs):
  // cache them the first time so they load offline later.
  if (url.hostname === 'fonts.gstatic.com' || url.hostname === 'fonts.googleapis.com' ||
      (url.hostname === 'www.gstatic.com' && url.pathname.startsWith('/firebasejs/'))) {
    event.respondWith((async () => {
      const cache = await caches.open(RUNTIME);
      const hit = await cache.match(req);
      if (hit) return hit;
      const res = await fetch(req);
      if (res.ok || res.type === 'opaque') cache.put(req, res.clone());
      return res;
    })());
  }
});
